import type { Calculator } from "./types";

export const financeCalculators: Calculator[] = [
  {
    slug: "loan-calculator",
    metaTitleKey: "finance.loan.metaTitle",
    metaDescriptionKey: "finance.loan.desc",
    titleKey: "finance.loan.title",
    category: "Finance",
    descriptionKey: "finance.loan.desc",
    formulaId: "loan",
    inputs: [
      {
        label: "finance.loan.principal",
        name: "principal",
        type: "number",
        unit: "$",
      },
      {
        label: "finance.loan.downPayment",
        name: "downPayment",
        type: "number",
        unit: "$",
      },
      { label: "finance.loan.rate", name: "rate", type: "number", unit: "%" },
      {
        label: "finance.loan.years",
        name: "years",
        type: "number",
        unit: "years",
      },

      {
        label: "finance.loan.paybackFrequency",
        name: "paybackFrequency",
        type: "select",
        options: [
          { value: "monthly", label: "finance.loan.monthly" },
          { value: "quarterly", label: "finance.loan.quarterly" },
          { value: "semiAnnually", label: "finance.loan.semiAnnually" },
          { value: "annually", label: "finance.loan.annually" },
        ],
      },
    ],

    result: {
      label: "finance.loan.result",
      explainKey: "finance.loan.resultExplain",
    },

    heading: "finance.loan.heading",
    tocheading: "finance.loan.tocTitle",
    toc: [
      { id: "about", labelKey: "finance.loan.tocabout" },
      { id: "formula", labelKey: "finance.loan.tocformula" },
      { id: "loan-payment-formula", labelKey: "finance.loan.tocloan" },
      { id: "example", labelKey: "finance.loan.tocexample" },
      { id: "why-matters", labelKey: "finance.loan.tocwhy" },
    ],

    sections: [
      {
        id: "about",
        titleKey: "finance.loan.aboutsection",
        contentKey: "finance.loan.aboutcontent",
      },
      {
        id: "formula",
        titleKey: "finance.loan.formulatitle",
        imageKey: "finance.loan.formulaImage",
        imageAltKey: "finance.loan.formulaImageAlt",
        introKey: "finance.loan.formulacontent",
        subsections: [
          {
            id: "loan-payment-formula",
            titleKey: "finance.loan.formulaSubtitle",
            formulaKey: "finance.loan.formula1",
            listKey: "finance.loan.formulaList",
          },
          {
            id: "example",
            titleKey: "finance.loan.formulaSubtitle2",
            introKey: "finance.loan.formulaSubcontent2",
            endKey: "finance.loan.formula2endcontent",
            formulas: ["finance.loan.formula2", "finance.loan.formula3"],
            resultKey: "finance.loan.formula3endcontent",
          },
          {
            id: "why-matters",
            titleKey: "finance.loan.formulasubtitle3",
            introKey: "finance.loan.formulasubcontent3",
            linkparacontent: "finance.loan.formulasub3extratext",
            linkparaKey: "finance.loan.formulasub3interlink",
            linkparaslug: "mortgage-calculator",
          },
        ],
      },
    ],

    faqTitleKey: "finance.loan.faqTitle",
    faqs: [
      { qKey: "finance.loan.faq.0.q", aKey: "finance.loan.faq.0.a" },
      { qKey: "finance.loan.faq.1.q", aKey: "finance.loan.faq.1.a" },
      { qKey: "finance.loan.faq.2.q", aKey: "finance.loan.faq.2.a" },
      { qKey: "finance.loan.faq.3.q", aKey: "finance.loan.faq.3.a" },
      { qKey: "finance.loan.faq.4.q", aKey: "finance.loan.faq.4.a" },
      { qKey: "finance.loan.faq.5.q", aKey: "finance.loan.faq.5.a" },
    ],
  },

  {
    slug: "mortgage-calculator",
    metaTitleKey: "finance.mortgage.metaTitle",
    metaDescriptionKey: "finance.mortgage.desc",
    titleKey: "finance.mortgage.title",
    category: "Finance",
    descriptionKey: "finance.mortgage.desc",
    inputs: [
      {
        label: "finance.mortgage.homePrice",
        name: "homePrice",
        type: "number",
        unit: "$",
      },
      {
        label: "finance.mortgage.downPayment",
        name: "downPayment",
        type: "number",
        unit: "$",
      },
      {
        label: "finance.mortgage.rate",
        name: "rate",
        type: "number",
        unit: "%",
      },
      {
        label: "finance.mortgage.years",
        name: "years",
        type: "number",
        unit: "years",
      },
      {
        label: "finance.mortgage.propertyTax",
        name: "propertyTax",
        type: "number",
        unit: "%",
      },
      {
        label: "finance.mortgage.homeInsurance",
        name: "homeInsurance",
        type: "number",
        unit: "$/yr",
      },
      {
        label: "finance.mortgage.hoaFees",
        name: "hoaFees",
        type: "number",
        unit: "$/mo",
      },
      {
        label: "finance.mortgage.downPaymentType",
        name: "downPaymentType",
        type: "select",
        options: [
          {
            label: "finance.mortgage.downPaymentTypePercent",
            value: "percent",
          },
          { label: "finance.mortgage.downPaymentTypeAmount", value: "amount" },
        ],
      },
    ],
    formulaId: "mortgage",

    result: {
      label: "finance.mortgage.result",
      explainKey: "finance.mortgage.resultExplain",
    },

    tocheading: "finance.mortgage.tocTitle",
    toc: [
      { id: "why-important", labelKey: "finance.mortgage.tocwhy" },
      { id: "how-works", labelKey: "finance.mortgage.tochowmortage" },
      { id: "why-use", labelKey: "finance.mortgage.tocwhyuse" },
      { id: "formula", labelKey: "finance.mortgage.tocmortageformula" },
      { id: "step-1", labelKey: "finance.mortgage.tocformulastep1" },
      { id: "step-2", labelKey: "finance.mortgage.tocformulastep2" },
      { id: "step-3", labelKey: "finance.mortgage.tocformulastep3" },
      { id: "how-to-use", labelKey: "finance.mortgage.tocformulahowto" },
      { id: "why-works", labelKey: "finance.mortgage.tocformulawhy" },
    ],

    heading: "finance.mortgage.heading",

    sections: [
      {
        id: "about",
        titleKey: "finance.mortgage.aboutH2",
        contentKey: "finance.mortgage.aboutContent",
        subsections: [
          {
            id: "why-important",
            titleKey: "finance.mortgage.whyTitle",
            introKey: "finance.mortgage.whyIntro",
            listKey: "finance.mortgage.whyList",
            endKey: "finance.mortgage.whyEnd",
          },
          {
            id: "how-works",
            titleKey: "finance.mortgage.howWorksTitle",
            contentKey: "finance.mortgage.howWorksContent",
            textKey: "finance.mortgage.howWorksInputTitle",
            listKey: "finance.mortgage.howWorksInputList",
            textKey2: "finance.mortgage.howWorksResulttext",
            lists: ["finance.mortgage.howWorksResultList"],
            endKey: "finance.mortgage.howWorksEnd",
          },
          {
            id: "why-use",
            titleKey: "finance.mortgage.whyUseTitle",
            contentKey: "finance.mortgage.whyUseContent",
          },
        ],
      },
      {
        id: "formula",
        titleKey: "finance.mortgage.formulaMainTitle",
        introKey: "finance.mortgage.formulaMainIntro",
        subsections: [
          {
            id: "formula-intro",
            textKey: "finance.mortgage.formulaSubIntro",
            formulaKey: "finance.mortgage.formulaMain",
            pointsKey: "finance.mortgage.formulaDefinitionList",
            endKey: "finance.mortgage.formulaEndText",
          },
          {
            id: "formula-image",
            imageKey: "finance.mortgage.formulaImage",
            imageAltKey: "finance.mortgage.formulaImageAlt",
          },
          {
            id: "step-1",
            titleKey: "finance.mortgage.step1Title",
            listKey: "finance.mortgage.step1List",
            endKey: "finance.mortgage.step1End",
          },
          {
            id: "step-2",
            titleKey: "finance.mortgage.step2Title",
            listKey: "finance.mortgage.step2ExampleList",
            subsections: [
              {
                id: "step-2-calc",
                contentKey: "finance.mortgage.step2CalcStep1",
              },
              {
                id: "step-2-formula",
                contentKey: "finance.mortgage.step2CalcStep2",
              },
              {
                id: "step-2-result",
                contentKey: "finance.mortgage.step2ResultMeaning",
              },
            ],
          },
          {
            id: "step-3",
            titleKey: "finance.mortgage.step3Title",
            contentKey: "finance.mortgage.step3Content",
            subsections: [
              {
                id: "total-example",
                titleKey: "finance.mortgage.totalExampleTitle",
                listKey: "finance.mortgage.totalExampleList",
                endKey: "finance.mortgage.totalExampleEnd",
              },
            ],
          },
          {
            id: "how-to-use",
            titleKey: "finance.mortgage.howToUseTitle",
            listKey: "finance.mortgage.howToUseList",
            linkparacontent: "finance.mortgage.howToUseEnd",
            linkparaKey: "finance.mortgage.interlink",
            linkparaslug: "loan-calculator",
          },
          {
            id: "why-works",
            titleKey: "finance.mortgage.whyWorksTitle",
            contentKey: "finance.mortgage.whyWorksContent",
          },
        ],
      },
    ],

    faqTitleKey: "finance.mortgage.faqTitle",
    faqs: [
      { qKey: "finance.mortgage.faq.0.q", aKey: "finance.mortgage.faq.0.a" },
      { qKey: "finance.mortgage.faq.1.q", aKey: "finance.mortgage.faq.1.a" },
      { qKey: "finance.mortgage.faq.2.q", aKey: "finance.mortgage.faq.2.a" },
      { qKey: "finance.mortgage.faq.3.q", aKey: "finance.mortgage.faq.3.a" },
      { qKey: "finance.mortgage.faq.4.q", aKey: "finance.mortgage.faq.4.a" },
      { qKey: "finance.mortgage.faq.5.q", aKey: "finance.mortgage.faq.5.a" },
    ],
  },
  {
    slug: "roi-calculator",
    metaTitleKey: "finance.roi.metaTitle",
    metaDescriptionKey: "finance.roi.desc",
    titleKey: "finance.roi.title",
    category: "Finance",
    descriptionKey: "finance.roi.desc",
    inputs: [
      {
        label: "finance.roi.investment",
        name: "investment",
        type: "number",
        unit: "$",
      },
      { label: "finance.roi.gain", name: "gain", type: "number", unit: "$" },
      { label: "finance.roi.costs", name: "costs", type: "number", unit: "$" },
    ],
    formulaId: "roi",

    result: {
      label: "finance.roi.result",
      explainKey: "finance.roi.resultExplain",
    },

    tocheading: "finance.roi.tocTitle",
    toc: [
      { id: "about", labelKey: "finance.roi.tocabout" },
      { id: "why-matters", labelKey: "finance.roi.tocwhy" },
      { id: "how-works", labelKey: "finance.roi.tochow" },
      { id: "formula", labelKey: "finance.roi.tocformula" },
      { id: "examples", labelKey: "finance.roi.tocexample" },
      { id: "results", labelKey: "finance.roi.tocresult" },
    ],

    heading: "finance.roi.heading",

    sections: [
      {
        id: "about",
        titleKey: "finance.roi.aboutsection",
        contentKey: "finance.roi.aboutcontent",
        subsections: [
          {
            id: "why-matters",
            titleKey: "finance.roi.whytitle",
            contentKey: "finance.roi.whycontent",
            listKey: "finance.roi.whylist",
            linkparacontent: "finance.roi.whyextratext",
            linkparaKey: "finance.roi.whyinterlink",
            linkparaslug: "breakeven-calculator",
          },
          {
            id: "how-works",
            titleKey: "finance.roi.howworkstitle",
            introKey: "finance.roi.howworksIntro",
            listKey: "finance.roi.howworkslist",
            lists: ["finance.roi.howworksresultlist"],
          },
          {
            id: "why-use",
            titleKey: "finance.roi.whyusetitle",
            contentKey: "finance.roi.whyusecontent",
          },
        ],
      },
      {
        id: "formula",
        titleKey: "finance.roi.formulatitle",
        subsections: [
          {
            id: "formula-main",
            formulas: ["finance.roi.formulamain", "finance.roi.formula2"],
            type: "formula",
          },
          {
            id: "formula-steps",
            titleKey: "finance.roi.stepTitle",
            listKey: "finance.roi.stepList",
            endKey: "finance.roi.stepEndText",
          },
          {
            id: "formula-image",
            imageKey: "finance.roi.formulaImage",
            imageAltKey: "finance.roi.formulaImageAlt",
          },
          {
            id: "examples",
            titleKey: "finance.roi.exampleTitle",
            subsections: [
              {
                id: "example-1",
                listKey: "finance.roi.exampleValues",
                subsections: [
                  {
                    id: "example-1-step-1",
                    contentKey: "finance.roi.exampleStep1",
                  },
                  {
                    id: "example-1-step-2",
                    contentKey: "finance.roi.exampleStep2",
                  },
                  {
                    id: "example-1-result",
                    contentKey: "finance.roi.exampleEnd",
                  },
                ],
              },
              {
                id: "example-2",
                titleKey: "finance.roi.example2Title",
                subsections: [
                  {
                    id: "investment-a",
                    listKey: "finance.roi.exampleA",
                  },
                  {
                    id: "investment-b",
                    listKey: "finance.roi.exampleB",
                  },
                  {
                    id: "comparison-result",
                    contentKey: "finance.roi.example2End",
                  },
                ],
              },
            ],
          },
          {
            id: "results",
            titleKey: "finance.roi.resultTitle",
            listKey: "finance.roi.resultList",
          },
          {
            id: "why-works",
            titleKey: "finance.roi.whysformulaTitle",
            contentKey: "finance.roi.whysformulaContent",
          },
        ],
      },
    ],

    faqTitleKey: "finance.roi.faqTitle",
    faqs: [
      { qKey: "finance.roi.faq.0.q", aKey: "finance.roi.faq.0.a" },
      { qKey: "finance.roi.faq.1.q", aKey: "finance.roi.faq.1.a" },
      { qKey: "finance.roi.faq.2.q", aKey: "finance.roi.faq.2.a" },
      { qKey: "finance.roi.faq.3.q", aKey: "finance.roi.faq.3.a" },
      { qKey: "finance.roi.faq.4.q", aKey: "finance.roi.faq.4.a" },
      { qKey: "finance.roi.faq.5.q", aKey: "finance.roi.faq.5.a" },
    ],
  },
  {
    slug: "breakeven-calculator",
    metaTitleKey: "finance.breakeven.metaTitle",
    metaDescriptionKey: "finance.breakeven.desc",
    titleKey: "finance.breakeven.title",
    category: "Finance",
    descriptionKey: "finance.breakeven.desc",

    inputs: [
      {
        label: "finance.breakeven.fixedCosts",
        name: "fixedCosts",
        type: "number",
        unit: "$",
      },
      {
        label: "finance.breakeven.variableCost",
        name: "variableCost",
        type: "number",
        unit: "$",
      },
      {
        label: "finance.breakeven.price",
        name: "price",
        type: "number",
        unit: "$",
      },
    ],

    result: {
      label: "finance.breakeven.result",
      explainKey: "finance.breakeven.resultExplain",
    },

    formulaId: "breakeven",
    tocheading: "finance.breakeven.tocTitle",
    toc: [
      { id: "about", labelKey: "finance.breakeven.tocabout" },
      { id: "why-matters", labelKey: "finance.breakeven.tocwhy" },
      { id: "how-works", labelKey: "finance.breakeven.tochowitworks" },
      { id: "why-use", labelKey: "finance.breakeven.tocwhyuse" },
    ],

    heading: "finance.breakeven.heading",

    sections: [
      {
        id: "about",
        titleKey: "finance.breakeven.aboutTitle",
        contentKey: "finance.breakeven.aboutContent",
        subsections: [
          {
            id: "why-matters",
            titleKey: "finance.breakeven.whyTitle",
            introKey: "finance.breakeven.whyIntro",
            listKey: "finance.breakeven.whyList",
            endKey: "finance.breakeven.whyEnd",
            linkparacontent: "finance.breakeven.interlinkExtraText",
            linkparaKey: "finance.breakeven.interlinkSlugText",
            linkparaslug: "roi-calculator",
          },
          {
            id: "how-works",
            titleKey: "finance.breakeven.howWorksTitle",
            introKey: "finance.breakeven.howWorksIntro",
            textKey: "finance.breakeven.howWorksListTitle",
            listKey: "finance.breakeven.howWorksList",
            textKey2: "finance.breakeven.howWorksResultTitle",
            lists: ["finance.breakeven.howWorksResultList"],
            endKey: "finance.breakeven.howWorksEnd",
          },
          {
            id: "why-use",
            titleKey: "finance.breakeven.whyUseTitle",
            contentKey: "finance.breakeven.whyUseContent",
          },
        ],
      },
      {
        id: "formula",
        titleKey: "finance.breakeven.formulatitle",
        introKey: "finance.breakeven.formulaintro",
        subsections: [
          {
            id: "formula-main",
            textKey: "finance.breakeven.mainFormulaText",
            formulaKey: "finance.breakeven.formula",
            endKey: "finance.breakeven.afterFormulaDesc",
          },
          {
            id: "formula-components",
            titleKey: "finance.breakeven.step1Title",
            listKey: "finance.breakeven.step1List",
            contentKey: "finance.breakeven.cvpLine",
          },
          {
            id: "revenue-formula",
            titleKey: "finance.breakeven.step2Title",
            textKey: "finance.breakeven.step2Desc",
            formulaKey: "finance.breakeven.step2Formula",
            endKey: "finance.breakeven.step2Explain",
          },
          {
            id: "formula-image",
            imageKey: "finance.breakeven.imageUrl",
            imageAltKey: "finance.breakeven.imageAlt",
          },
          {
            id: "examples",
            titleKey: "finance.breakeven.exampleTitle",
            listKey: "finance.breakeven.exampleList",
            subsections: [
              {
                id: "example-step-1",
                contentKey: "finance.breakeven.exampleStep1",
              },
              {
                id: "example-step-2",
                contentKey: "finance.breakeven.exampleStep2",
              },
              {
                id: "example-result",
                contentKey: "finance.breakeven.exampleExplain",
              },
            ],
          },
          {
            id: "interpreting",
            titleKey: "finance.breakeven.interpretingTitle",
            listKey: "finance.breakeven.interpretingList",
            endKey: "finance.breakeven.interpretDesc",
          },
          {
            id: "why-works",
            titleKey: "finance.breakeven.whyWorksTitle",
            contentKey: "finance.breakeven.whyWorksDesc",
          },
        ],
      },
    ],

    faqTitleKey: "finance.breakeven.faqTitle",
    faqs: [
      { qKey: "finance.breakeven.faq.0.q", aKey: "finance.breakeven.faq.0.a" },
      { qKey: "finance.breakeven.faq.1.q", aKey: "finance.breakeven.faq.1.a" },
      { qKey: "finance.breakeven.faq.2.q", aKey: "finance.breakeven.faq.2.a" },
      { qKey: "finance.breakeven.faq.3.q", aKey: "finance.breakeven.faq.3.a" },
      { qKey: "finance.breakeven.faq.4.q", aKey: "finance.breakeven.faq.4.a" },
      { qKey: "finance.breakeven.faq.5.q", aKey: "finance.breakeven.faq.5.a" },
    ],
  },

  {
    slug: "inflation-calculator",
    metaTitleKey: "finance.inflation.metaTitle",
    metaDescriptionKey: "finance.inflation.desc",
    titleKey: "finance.inflation.title",
    category: "Finance",
    descriptionKey: "finance.inflation.desc",
    inputs: [
      {
        label: "finance.inflation.amount",
        name: "amount",
        type: "number",
        unit: "$",
      },
      {
        label: "finance.inflation.years",
        name: "years",
        type: "number",
        unit: "years",
      },
      {
        label: "finance.inflation.rate",
        name: "rate",
        type: "number",
        unit: "%",
      },
      {
        label: "finance.inflation.mode",
        name: "mode",
        type: "select",
        options: [
          { value: "future", label: "finance.inflation.mode_future" },
          { value: "past", label: "finance.inflation.mode_past" },
        ],
      },
    ],
    result: {
      label: "finance.inflation.result",
      explainKey: "finance.inflation.resultExplain",
    },

    formulaId: "inflation",
    tocheading: "finance.inflation.tocTitle",
    toc: [
      { id: "why-matters", labelKey: "finance.inflation.tocwhy" },
      { id: "how-works", labelKey: "finance.inflation.tochowitworks" },
      { id: "why-use", labelKey: "finance.inflation.tocwhyuse" },
      { id: "step-1", labelKey: "finance.inflation.tocsteps1" },
      { id: "step-2", labelKey: "finance.inflation.tocsteps2" },
      { id: "results", labelKey: "finance.inflation.tocresults" },
      { id: "why-works", labelKey: "finance.inflation.tocwhyformula" },
    ],

    heading: "finance.inflation.heading",

    sections: [
      {
        id: "about",
        titleKey: "finance.inflation.aboutTitle",
        contentKey: "finance.inflation.aboutDesc",
        subsections: [
          {
            id: "why-matters",
            titleKey: "finance.inflation.whyTitle",
            contentKey: "finance.inflation.whyDesc",
            pointsKey: "finance.inflation.whyPoints",
          },
          {
            id: "how-works",
            titleKey: "finance.inflation.howTitle",
            contentKey: "finance.inflation.howDesc",
            listKey: "finance.inflation.howNeed",
            textKey: "finance.inflation.howResult",
            lists: ["finance.inflation.howResult"],
          },
          {
            id: "why-use",
            titleKey: "finance.inflation.whyUseTitle",
            contentKey: "finance.inflation.whyUseDesc",
          },
        ],
      },
      {
        id: "formula",
        titleKey: "finance.inflation.formulatitle",
        introKey: "finance.inflation.formulaintro",
        subsections: [
          {
            id: "formula-main",
            formulaKey: "finance.inflation.formula1",
            endKey: "finance.inflation.formula1endtext",
          },
          {
            id: "formula-image",
            imageKey: "finance.inflation.formulaImage",
            imageAltKey: "finance.inflation.formulaImageAlt",
          },
          {
            id: "step-1",
            titleKey: "finance.inflation.steps1title",
            introKey: "finance.inflation.steps1intro",
            listKey: "finance.inflation.steps1list",
            endKey: "finance.inflation.steps1endtext",
          },
          {
            id: "step-2",
            titleKey: "finance.inflation.steps2title",
            introKey: "finance.inflation.steps2intro",
            formulaKey: "finance.inflation.steps2formula",
            endKey: "finance.inflation.steps2endtext",
          },
          {
            id: "examples",
            titleKey: "finance.inflation.exampletitle",
            introKey: "finance.inflation.exampleintro",
            subsections: [
              {
                id: "example-1",
                listKey: "finance.inflation.example1list",
                subsections: [
                  {
                    id: "example-1-step",
                    labelKey: "finance.inflation.examplestep1",
                    lists: ["finance.inflation.examplelist"],
                    endKey: "finance.inflation.example2end",
                  },
                ],
              },
              {
                id: "example-2",
                titleKey: "finance.inflation.exampletitle2",
                introKey: "finance.inflation.example2intro",
                lists: ["finance.inflation.example2list"],
                endKey: "finance.inflation.example2endtext",
              },
            ],
          },
          {
            id: "results",
            titleKey: "finance.inflation.howtotitle",
            introKey: "finance.inflation.howtointro",
            listKey: "finance.inflation.howtolist",
            linkparacontent: "finance.inflation.howtoendtext",
            linkparaKey: "finance.inflation.howtoInterLink",
            linkparaslug: "roi-calculator",
          },
          {
            id: "why-works",
            titleKey: "finance.inflation.whyformulaworkstitle",
            contentKey: "finance.inflation.whyformulaworkscontent",
          },
        ],
      },
    ],

    faqTitleKey: "finance.inflation.faqTitle",
    faqs: [
      { qKey: "finance.inflation.faq.0.q", aKey: "finance.inflation.faq.0.a" },
      { qKey: "finance.inflation.faq.1.q", aKey: "finance.inflation.faq.1.a" },
      { qKey: "finance.inflation.faq.2.q", aKey: "finance.inflation.faq.2.a" },
      { qKey: "finance.inflation.faq.3.q", aKey: "finance.inflation.faq.3.a" },
      { qKey: "finance.inflation.faq.4.q", aKey: "finance.inflation.faq.4.a" },
      { qKey: "finance.inflation.faq.5.q", aKey: "finance.inflation.faq.5.a" },
    ],
  },
  {
    slug: "currency-converter",
    metaTitleKey: "finance.currency.metaTitle",
    metaDescriptionKey: "finance.currency.desc",
    titleKey: "finance.currency.title",
    category: "Finance",
    descriptionKey: "finance.currency.desc",

    inputs: [
      {
        label: "finance.currency.amount",
        name: "amount",
        type: "number",
        unit: "$",
      },
      {
        label: "finance.currency.fromCurrency",
        name: "fromCurrency",
        type: "select",
        options: [
          { value: "ADA", label: "finance.currency.ada" },
          { value: "AED", label: "finance.currency.aed" },
          { value: "AFN", label: "finance.currency.afn" },
          { value: "ALL", label: "finance.currency.all" },
          { value: "AMD", label: "finance.currency.amd" },
          { value: "ANG", label: "finance.currency.ang" },
          { value: "AOA", label: "finance.currency.aoa" },
          { value: "ARB", label: "finance.currency.arb" },
          { value: "ARS", label: "finance.currency.ars" },
          { value: "AUD", label: "finance.currency.aud" },
          { value: "AWG", label: "finance.currency.awg" },
          { value: "AZN", label: "finance.currency.azn" },
          { value: "BAM", label: "finance.currency.bam" },
          { value: "BBD", label: "finance.currency.bbd" },
          { value: "BDT", label: "finance.currency.bdt" },
          { value: "BGN", label: "finance.currency.bgn" },
          { value: "BHD", label: "finance.currency.bhd" },
          { value: "BIF", label: "finance.currency.bif" },
          { value: "BMD", label: "finance.currency.bmd" },
          { value: "BND", label: "finance.currency.bnd" },
          { value: "BOB", label: "finance.currency.bob" },
          { value: "BRL", label: "finance.currency.brl" },
          { value: "BSD", label: "finance.currency.bsd" },
          { value: "BTN", label: "finance.currency.btn" },
          { value: "BWP", label: "finance.currency.bwp" },
          { value: "BYN", label: "finance.currency.byn" },
          { value: "BZD", label: "finance.currency.bzd" },
          { value: "CAD", label: "finance.currency.cad" },
          { value: "CDF", label: "finance.currency.cdf" },
          { value: "CHF", label: "finance.currency.chf" },
          { value: "CLP", label: "finance.currency.clp" },
          { value: "CNY", label: "finance.currency.cny" },
          { value: "COP", label: "finance.currency.cop" },
          { value: "CRC", label: "finance.currency.crc" },
          { value: "CUP", label: "finance.currency.cup" },
          { value: "CVE", label: "finance.currency.cve" },
          { value: "CZK", label: "finance.currency.czk" },
          { value: "DJF", label: "finance.currency.djf" },
          { value: "DKK", label: "finance.currency.dkk" },
          { value: "DOP", label: "finance.currency.dop" },
          { value: "DZD", label: "finance.currency.dzd" },
          { value: "EGP", label: "finance.currency.egp" },
          { value: "ERN", label: "finance.currency.ern" },
          { value: "ETB", label: "finance.currency.etb" },
          { value: "EUR", label: "finance.currency.eur" },
          { value: "FJD", label: "finance.currency.fjd" },
          { value: "FKP", label: "finance.currency.fkp" },
          { value: "GBP", label: "finance.currency.gbp" },
          { value: "GEL", label: "finance.currency.gel" },
          { value: "GHS", label: "finance.currency.ghs" },
          { value: "GIP", label: "finance.currency.gip" },
          { value: "GMD", label: "finance.currency.gmd" },
          { value: "GNF", label: "finance.currency.gnf" },
          { value: "GTQ", label: "finance.currency.gtq" },
          { value: "GYD", label: "finance.currency.gyd" },
          { value: "HKD", label: "finance.currency.hkd" },
          { value: "HNL", label: "finance.currency.hnl" },
          { value: "HRK", label: "finance.currency.hrk" },
          { value: "HTG", label: "finance.currency.htg" },
          { value: "HUF", label: "finance.currency.huf" },
          { value: "IDR", label: "finance.currency.idr" },
          { value: "ILS", label: "finance.currency.ils" },
          { value: "INR", label: "finance.currency.inr" },
          { value: "IQD", label: "finance.currency.iqd" },
          { value: "IRR", label: "finance.currency.irr" },
          { value: "ISK", label: "finance.currency.isk" },
          { value: "JMD", label: "finance.currency.jmd" },
          { value: "JOD", label: "finance.currency.jod" },
          { value: "JPY", label: "finance.currency.jpy" },
          { value: "KES", label: "finance.currency.kes" },
          { value: "KGS", label: "finance.currency.kgs" },
          { value: "KHR", label: "finance.currency.khr" },
          { value: "KMF", label: "finance.currency.kmf" },
          { value: "KRW", label: "finance.currency.krw" },
          { value: "KWD", label: "finance.currency.kwd" },
          { value: "KYD", label: "finance.currency.kyd" },
          { value: "KZT", label: "finance.currency.kzt" },
          { value: "LAK", label: "finance.currency.lak" },
          { value: "LBP", label: "finance.currency.lbp" },
          { value: "LKR", label: "finance.currency.lkr" },
          { value: "LRD", label: "finance.currency.lrd" },
          { value: "LSL", label: "finance.currency.lsl" },
          { value: "LYD", label: "finance.currency.lyd" },
          { value: "MAD", label: "finance.currency.mad" },
          { value: "MDL", label: "finance.currency.mdl" },
          { value: "MGA", label: "finance.currency.mga" },
          { value: "MKD", label: "finance.currency.mkd" },
          { value: "MMK", label: "finance.currency.mmk" },
          { value: "MNT", label: "finance.currency.mnt" },
          { value: "MOP", label: "finance.currency.mop" },
          { value: "MRU", label: "finance.currency.mru" },
          { value: "MUR", label: "finance.currency.mur" },
          { value: "MVR", label: "finance.currency.mvr" },
          { value: "MWK", label: "finance.currency.mwk" },
          { value: "MXN", label: "finance.currency.mxn" },
          { value: "MYR", label: "finance.currency.myr" },
          { value: "MZN", label: "finance.currency.mzn" },
          { value: "NAD", label: "finance.currency.nad" },
          { value: "NGN", label: "finance.currency.ngn" },
          { value: "NIO", label: "finance.currency.nio" },
          { value: "NOK", label: "finance.currency.nok" },
          { value: "NPR", label: "finance.currency.npr" },
          { value: "NZD", label: "finance.currency.nzd" },
          { value: "OMR", label: "finance.currency.omr" },
          { value: "PAB", label: "finance.currency.pab" },
          { value: "PEN", label: "finance.currency.pen" },
          { value: "PGK", label: "finance.currency.pgk" },
          { value: "PHP", label: "finance.currency.php" },
          { value: "PKR", label: "finance.currency.pkr" },
          { value: "PLN", label: "finance.currency.pln" },
          { value: "PYG", label: "finance.currency.pyg" },
          { value: "QAR", label: "finance.currency.qar" },
          { value: "RON", label: "finance.currency.ron" },
          { value: "RSD", label: "finance.currency.rsd" },
          { value: "RUB", label: "finance.currency.rub" },
          { value: "RWF", label: "finance.currency.rwf" },
          { value: "SAR", label: "finance.currency.sar" },
          { value: "SCR", label: "finance.currency.scr" },
          { value: "SDG", label: "finance.currency.sdg" },
          { value: "SEK", label: "finance.currency.sek" },
          { value: "SGD", label: "finance.currency.sgd" },
          { value: "SLL", label: "finance.currency.sll" },
          { value: "SOS", label: "finance.currency.sos" },
          { value: "SRD", label: "finance.currency.srd" },
          { value: "STN", label: "finance.currency.stn" },
          { value: "SYP", label: "finance.currency.syp" },
          { value: "SZL", label: "finance.currency.szl" },
          { value: "THB", label: "finance.currency.thb" },
          { value: "TND", label: "finance.currency.tnd" },
          { value: "TOP", label: "finance.currency.top" },
          { value: "TRY", label: "finance.currency.try" },
          { value: "TTD", label: "finance.currency.ttd" },
          { value: "TWD", label: "finance.currency.twd" },
          { value: "TZS", label: "finance.currency.tzs" },
          { value: "UAH", label: "finance.currency.uah" },
          { value: "UGX", label: "finance.currency.ugx" },
          { value: "USD", label: "finance.currency.usd" },
          { value: "UYU", label: "finance.currency.uyu" },
          { value: "UZS", label: "finance.currency.uzs" },
          { value: "VES", label: "finance.currency.ves" },
          { value: "VND", label: "finance.currency.vnd" },
          { value: "VUV", label: "finance.currency.vuv" },
          { value: "WST", label: "finance.currency.wst" },
          { value: "XAF", label: "finance.currency.xaf" },
          { value: "XCD", label: "finance.currency.xcd" },
          { value: "XOF", label: "finance.currency.xof" },
          { value: "XPF", label: "finance.currency.xpf" },
          { value: "YER", label: "finance.currency.yer" },
          { value: "ZAR", label: "finance.currency.zar" },
          { value: "ZMW", label: "finance.currency.zmw" },
          { value: "ZWL", label: "finance.currency.zwl" },
        ],
      },
      {
        label: "finance.currency.toCurrency",
        name: "toCurrency",
        type: "select",
        options: [
          { value: "ADA", label: "finance.currency.ada" },
          { value: "AED", label: "finance.currency.aed" },
          { value: "AFN", label: "finance.currency.afn" },
          { value: "ALL", label: "finance.currency.all" },
          { value: "AMD", label: "finance.currency.amd" },
          { value: "ANG", label: "finance.currency.ang" },
          { value: "AOA", label: "finance.currency.aoa" },
          { value: "ARB", label: "finance.currency.arb" },
          { value: "ARS", label: "finance.currency.ars" },
          { value: "AUD", label: "finance.currency.aud" },
          { value: "AWG", label: "finance.currency.awg" },
          { value: "AZN", label: "finance.currency.azn" },
          { value: "BAM", label: "finance.currency.bam" },
          { value: "BBD", label: "finance.currency.bbd" },
          { value: "BDT", label: "finance.currency.bdt" },
          { value: "BGN", label: "finance.currency.bgn" },
          { value: "BHD", label: "finance.currency.bhd" },
          { value: "BIF", label: "finance.currency.bif" },
          { value: "BMD", label: "finance.currency.bmd" },
          { value: "BND", label: "finance.currency.bnd" },
          { value: "BOB", label: "finance.currency.bob" },
          { value: "BRL", label: "finance.currency.brl" },
          { value: "BSD", label: "finance.currency.bsd" },
          { value: "BTN", label: "finance.currency.btn" },
          { value: "BWP", label: "finance.currency.bwp" },
          { value: "BYN", label: "finance.currency.byn" },
          { value: "BZD", label: "finance.currency.bzd" },
          { value: "CAD", label: "finance.currency.cad" },
          { value: "CDF", label: "finance.currency.cdf" },
          { value: "CHF", label: "finance.currency.chf" },
          { value: "CLP", label: "finance.currency.clp" },
          { value: "CNY", label: "finance.currency.cny" },
          { value: "COP", label: "finance.currency.cop" },
          { value: "CRC", label: "finance.currency.crc" },
          { value: "CUP", label: "finance.currency.cup" },
          { value: "CVE", label: "finance.currency.cve" },
          { value: "CZK", label: "finance.currency.czk" },
          { value: "DJF", label: "finance.currency.djf" },
          { value: "DKK", label: "finance.currency.dkk" },
          { value: "DOP", label: "finance.currency.dop" },
          { value: "DZD", label: "finance.currency.dzd" },
          { value: "EGP", label: "finance.currency.egp" },
          { value: "ERN", label: "finance.currency.ern" },
          { value: "ETB", label: "finance.currency.etb" },
          { value: "EUR", label: "finance.currency.eur" },
          { value: "FJD", label: "finance.currency.fjd" },
          { value: "FKP", label: "finance.currency.fkp" },
          { value: "GBP", label: "finance.currency.gbp" },
          { value: "GEL", label: "finance.currency.gel" },
          { value: "GHS", label: "finance.currency.ghs" },
          { value: "GIP", label: "finance.currency.gip" },
          { value: "GMD", label: "finance.currency.gmd" },
          { value: "GNF", label: "finance.currency.gnf" },
          { value: "GTQ", label: "finance.currency.gtq" },
          { value: "GYD", label: "finance.currency.gyd" },
          { value: "HKD", label: "finance.currency.hkd" },
          { value: "HNL", label: "finance.currency.hnl" },
          { value: "HRK", label: "finance.currency.hrk" },
          { value: "HTG", label: "finance.currency.htg" },
          { value: "HUF", label: "finance.currency.huf" },
          { value: "IDR", label: "finance.currency.idr" },
          { value: "ILS", label: "finance.currency.ils" },
          { value: "INR", label: "finance.currency.inr" },
          { value: "IQD", label: "finance.currency.iqd" },
          { value: "IRR", label: "finance.currency.irr" },
          { value: "ISK", label: "finance.currency.isk" },
          { value: "JMD", label: "finance.currency.jmd" },
          { value: "JOD", label: "finance.currency.jod" },
          { value: "JPY", label: "finance.currency.jpy" },
          { value: "KES", label: "finance.currency.kes" },
          { value: "KGS", label: "finance.currency.kgs" },
          { value: "KHR", label: "finance.currency.khr" },
          { value: "KMF", label: "finance.currency.kmf" },
          { value: "KRW", label: "finance.currency.krw" },
          { value: "KWD", label: "finance.currency.kwd" },
          { value: "KYD", label: "finance.currency.kyd" },
          { value: "KZT", label: "finance.currency.kzt" },
          { value: "LAK", label: "finance.currency.lak" },
          { value: "LBP", label: "finance.currency.lbp" },
          { value: "LKR", label: "finance.currency.lkr" },
          { value: "LRD", label: "finance.currency.lrd" },
          { value: "LSL", label: "finance.currency.lsl" },
          { value: "LYD", label: "finance.currency.lyd" },
          { value: "MAD", label: "finance.currency.mad" },
          { value: "MDL", label: "finance.currency.mdl" },
          { value: "MGA", label: "finance.currency.mga" },
          { value: "MKD", label: "finance.currency.mkd" },
          { value: "MMK", label: "finance.currency.mmk" },
          { value: "MNT", label: "finance.currency.mnt" },
          { value: "MOP", label: "finance.currency.mop" },
          { value: "MRU", label: "finance.currency.mru" },
          { value: "MUR", label: "finance.currency.mur" },
          { value: "MVR", label: "finance.currency.mvr" },
          { value: "MWK", label: "finance.currency.mwk" },
          { value: "MXN", label: "finance.currency.mxn" },
          { value: "MYR", label: "finance.currency.myr" },
          { value: "MZN", label: "finance.currency.mzn" },
          { value: "NAD", label: "finance.currency.nad" },
          { value: "NGN", label: "finance.currency.ngn" },
          { value: "NIO", label: "finance.currency.nio" },
          { value: "NOK", label: "finance.currency.nok" },
          { value: "NPR", label: "finance.currency.npr" },
          { value: "NZD", label: "finance.currency.nzd" },
          { value: "OMR", label: "finance.currency.omr" },
          { value: "PAB", label: "finance.currency.pab" },
          { value: "PEN", label: "finance.currency.pen" },
          { value: "PGK", label: "finance.currency.pgk" },
          { value: "PHP", label: "finance.currency.php" },
          { value: "PKR", label: "finance.currency.pkr" },
          { value: "PLN", label: "finance.currency.pln" },
          { value: "PYG", label: "finance.currency.pyg" },
          { value: "QAR", label: "finance.currency.qar" },
          { value: "RON", label: "finance.currency.ron" },
          { value: "RSD", label: "finance.currency.rsd" },
          { value: "RUB", label: "finance.currency.rub" },
          { value: "RWF", label: "finance.currency.rwf" },
          { value: "SAR", label: "finance.currency.sar" },
          { value: "SCR", label: "finance.currency.scr" },
          { value: "SDG", label: "finance.currency.sdg" },
          { value: "SEK", label: "finance.currency.sek" },
          { value: "SGD", label: "finance.currency.sgd" },
          { value: "SLL", label: "finance.currency.sll" },
          { value: "SOS", label: "finance.currency.sos" },
          { value: "SRD", label: "finance.currency.srd" },
          { value: "STN", label: "finance.currency.stn" },
          { value: "SYP", label: "finance.currency.syp" },
          { value: "SZL", label: "finance.currency.szl" },
          { value: "THB", label: "finance.currency.thb" },
          { value: "TND", label: "finance.currency.tnd" },
          { value: "TOP", label: "finance.currency.top" },
          { value: "TRY", label: "finance.currency.try" },
          { value: "TTD", label: "finance.currency.ttd" },
          { value: "TWD", label: "finance.currency.twd" },
          { value: "TZS", label: "finance.currency.tzs" },
          { value: "UAH", label: "finance.currency.uah" },
          { value: "UGX", label: "finance.currency.ugx" },
          { value: "USD", label: "finance.currency.usd" },
          { value: "UYU", label: "finance.currency.uyu" },
          { value: "UZS", label: "finance.currency.uzs" },
          { value: "VES", label: "finance.currency.ves" },
          { value: "VND", label: "finance.currency.vnd" },
          { value: "VUV", label: "finance.currency.vuv" },
          { value: "WST", label: "finance.currency.wst" },
          { value: "XAF", label: "finance.currency.xaf" },
          { value: "XCD", label: "finance.currency.xcd" },
          { value: "XOF", label: "finance.currency.xof" },
          { value: "XPF", label: "finance.currency.xpf" },
          { value: "YER", label: "finance.currency.yer" },
          { value: "ZAR", label: "finance.currency.zar" },
          { value: "ZMW", label: "finance.currency.zmw" },
          { value: "ZWL", label: "finance.currency.zwl" },
        ],
      },
    ],

    formulaId: "currency",

    result: {
      label: "finance.currency.result",
      explainKey: "finance.currency.resultExplain",
    },
    tocheading: "finance.currency.tocTitle",
    toc: [
      { id: "about", labelKey: "finance.currency.tocabout" },
      { id: "conversion", labelKey: "finance.currency.tocconversion" },
      { id: "formula", labelKey: "finance.currency.tocformula" },
      { id: "example", labelKey: "finance.currency.tocexample" },
      { id: "accurate", labelKey: "finance.currency.tocaccurateconversion" },
    ],

    heading: "finance.currency.heading",

    sections: [
      {
        id: "about",
        titleKey: "finance.currency.aboutTitle",
        contentKey: "finance.currency.aboutDesc",
        linkparacontent: "finance.currency.aboutExtratext",
        linkparaKey: "finance.currency.aboutInterLink",
        linkparaslug: "inflation-calculator",
        subsections: [
          {
            id: "conversion",
            titleKey: "finance.currency.conversionTitle",
            contentKey: "finance.currency.conversioncontent",
            textKey: "finance.currency.keyhighlight",
            listKey: "finance.currency.keyhighlightList",
            endKey: "finance.currency.keyhighlightsendtext",
          },
        ],
      },
      {
        id: "formula",
        titleKey: "finance.currency.formulatitle",
        subsections: [
          {
            id: "formula-how",
            titleKey: "finance.currency.formulasubtitle",
            introKey: "finance.currency.formulasubintro",
            formulaKey: "finance.currency.formula1",
            pointsKey: "finance.currency.formula1list",
          },
          {
            id: "formula-image",
            imageKey: "finance.currency.formulaImage",
            imageAltKey: "finance.currency.formulaImageAlt",
          },
          {
            id: "example",
            titleKey: "finance.currency.exampletitle",
            introKey: "finance.currency.exampleintro",
            formulaKey: "finance.currency.exampleformula",
            endKey: "finance.currency.exampleendtext",
          },
          {
            id: "accurate",
            titleKey: "finance.currency.accuratetitle",
            subtitleKey: "finance.currency.accuratesubtitle",
            contentKey: "finance.currency.accuratesubcontent",
            listKey: "finance.currency.accuratesublist",
            endKey: "finance.currency.accuratesubend",
          },
        ],
      },
    ],

    faqTitleKey: "finance.currency.faqTitle",
    faqs: [
      { qKey: "finance.currency.faq.0.q", aKey: "finance.currency.faq.0.a" },
      { qKey: "finance.currency.faq.1.q", aKey: "finance.currency.faq.1.a" },
      { qKey: "finance.currency.faq.2.q", aKey: "finance.currency.faq.2.a" },
      { qKey: "finance.currency.faq.3.q", aKey: "finance.currency.faq.3.a" },
      { qKey: "finance.currency.faq.4.q", aKey: "finance.currency.faq.4.a" },
      { qKey: "finance.currency.faq.5.q", aKey: "finance.currency.faq.5.a" },
    ],
  },

  {
    slug: "discount-calculator",
    metaTitleKey: "finance.discount.metaTitle",
    metaDescriptionKey: "finance.discount.metadesc",
    titleKey: "finance.discount.metaTitle",
    category: "Finance",
    descriptionKey: "finance.discount.metadesc",
    heading: "finance.discount.heading",
    formulaId: "discount",

    inputs: [
      {
        label: "finance.discount.originalPrice",
        name: "originalPrice",
        type: "number",
        unit: "₨",
      },
      {
        label: "finance.discount.discountPercent",
        name: "discountPercent",
        type: "number",
        unit: "%",
      },
      {
        label: "finance.discount.taxRate",
        name: "taxRate",
        type: "number",
        unit: "%",
      },
    ],

    result: {
      label: "finance.discount.result",
      explainKey: "finance.discount.resultExplain",
    },
    tocheading: "finance.discount.tocTitle",
    toc: [
      { id: "why-matters", labelKey: "finance.discount.tocwhyitmatters" },
      { id: "how-works", labelKey: "finance.discount.tochowitworks" },
      { id: "why-use", labelKey: "finance.discount.tocwhyuse" },
      { id: "examples", labelKey: "finance.discount.tocexample" },
      { id: "multiple-discounts", labelKey: "finance.discount.tocmultiple" },
      { id: "result", labelKey: "finance.discount.tocresult" },
      { id: "why-formula-works", labelKey: "finance.discount.tocwhyformula" },
    ],

    sections: [
      {
        id: "intro",
        titleKey: "finance.discount.aboutTitle",
        contentKey: "finance.discount.aboutDesc",
        subsections: [
          {
            id: "why-matters",
            titleKey: "finance.discount.whytitle",
            introKey: "finance.discount.whydesc",
            linkparacontent: "finance.discount.whydesc",
            linkparaKey: "finance.discount.interlink",
            linkparaslug: "savings-calculator",
          },
          {
            id: "how-works",
            titleKey: "finance.discount.howItWorksTitle",
            introKey: "finance.discount.howitworksintro",
            listKey: "finance.discount.howItWorkslist1",
            contentKey: "finance.discount.howitworkstext",
            listKey2: "finance.discount.howItWorkslist2",
            endKey: "finance.discount.howitworksend",
          },
          {
            id: "why-use",
            titleKey: "finance.discount.whyUseTitle",
            introKey: "finance.discount.whyUsepara",
          },
        ],
      },

      {
        id: "formula",
        titleKey: "finance.discount.formulatitle",
        introKey: "finance.discount.formulaintro",
        subsections: [
          {
            id: "main-formula",
            formulaKey: "finance.discount.formula1",
            type: "formula",
            endKey: "finance.discount.formulaendtext",
          },
          {
            id: "step1",
            titleKey: "finance.discount.step1title",
            formulaKey: "finance.discount.step1formula",
            endKey: "finance.discount.step1endtext",
          },
          {
            id: "step2",
            titleKey: "finance.discount.step2title",
            formulaKey: "finance.discount.step2formula",
            endKey: "finance.discount.step2endtext",
          },
          {
            id: "examples",
            titleKey: "finance.discount.exampletitle",
            imageKey: "finance.discount.formulaImage",
            imageAltKey: "finance.discount.formulaImageAlt",
            introKey: "finance.discount.exampleintro",
            listKey: "finance.discount.examplelist",
            formulas: ["finance.discount.stepslist"],
            endKey: "finance.discount.stepsend",
          },
          {
            id: "multiple-discounts",
            titleKey: "finance.discount.multititle",
            contentKey: "finance.discount.multidesc",
            listKey: "finance.discount.multilist",
            formulas: [
              "finance.discount.multiformula",
              "finance.discount.multiformula2",
            ],
            endKey: "finance.discount.multiendtext",
          },
          {
            id: "result",
            titleKey: "finance.discount.resulttitle",
            contentKey: "finance.discount.resultdesc",
            listKey: "finance.discount.resultlist",
          },
          {
            id: "why-formula-works",
            titleKey: "finance.discount.whyformulatitle",
            contentKey: "finance.discount.whyformuladesc",
          },
        ],
      },
    ],

    faqTitleKey: "finance.discount.faqTitle",
    faqs: [
      { qKey: "finance.discount.faq.0.q", aKey: "finance.discount.faq.0.a" },
      { qKey: "finance.discount.faq.1.q", aKey: "finance.discount.faq.1.a" },
      { qKey: "finance.discount.faq.2.q", aKey: "finance.discount.faq.2.a" },
      { qKey: "finance.discount.faq.3.q", aKey: "finance.discount.faq.3.a" },
      { qKey: "finance.discount.faq.4.q", aKey: "finance.discount.faq.4.a" },
      { qKey: "finance.discount.faq.5.q", aKey: "finance.discount.faq.5.a" },
    ],
  },

  {
    slug: "savings-calculator",
    metaTitleKey: "finance.savings.metaTitle",
    metaDescriptionKey: "finance.savings.metadesc",
    titleKey: "finance.savings.metaTitle",
    category: "Finance",
    descriptionKey: "finance.savings.metadesc",
    heading: "finance.savings.heading",
    formulaId: "savings",

    inputs: [
      {
        label: "finance.savings.initialDeposit",
        name: "initialDeposit",
        type: "number",
        unit: "$",
      },
      {
        label: "finance.savings.monthlyDeposit",
        name: "monthlyDeposit",
        type: "number",
        unit: "$",
      },
      {
        label: "finance.savings.interestRate",
        name: "interestRate",
        type: "number",
        unit: "%",
      },
      {
        label: "finance.savings.timePeriod",
        name: "timePeriod",
        type: "number",
        unit: "years",
      },
      {
        label: "finance.savings.compoundFrequency",
        name: "compoundFrequency",
        type: "select",
        options: [
          { value: "monthly", label: "finance.savings.compoundMonthly" },
          { value: "quarterly", label: "finance.savings.compoundQuarterly" },
          { value: "yearly", label: "finance.savings.compoundYearly" },
        ],
      },
      {
        label: "finance.savings.inflationRate",
        name: "inflationRate",
        type: "number",
        unit: "%",
      },
    ],

    result: {
      label: "finance.savings.result",
      explainKey: "finance.savings.resultExplain",
    },
    tocheading: "finance.savings.tocTitle",
    toc: [
      { id: "about", labelKey: "finance.savings.tocabout" },
      { id: "track-progress", labelKey: "finance.savings.toctrackprogress" },
      { id: "features", labelKey: "finance.savings.tocfeatures" },
      { id: "formula", labelKey: "finance.savings.tocformula" },
      { id: "examples", labelKey: "finance.savings.tocexample" },
      { id: "why-use", labelKey: "finance.savings.tocwhyuse" },
      { id: "how-to-use", labelKey: "finance.savings.tochowto" },
    ],

    sections: [
      {
        id: "intro",
        titleKey: "finance.savings.aboutTitle",
        contentKey: "finance.savings.aboutDesc",
        linkparacontent: "finance.savings.aboutDesc",
        linkparaKey: "finance.savings.interlink",
        linkparaslug: "discount-calculator",
        subsections: [
          {
            id: "track-progress",
            titleKey: "finance.savings.trackProgressTitle",
            introKey: "finance.savings.trackProgressDesc",
          },
          {
            id: "features",
            titleKey: "finance.savings.featuresTitle",
            listKey: "finance.savings.featuresList",
          },
        ],
      },

      {
        id: "formula",
        titleKey: "finance.savings.formulatitle",
        introKey: "finance.savings.howitworksintro",
        subsections: [
          {
            id: "main-formula",
            imageKey: "finance.savings.formulaImage",
            imageAltKey: "finance.savings.formulaImageAlt",
            formulaKey: "finance.savings.formula",
            type: "formula",
            listKey: "finance.savings.formulaExplanation",
          },
          {
            id: "simple-explanation",
            titleKey: "finance.savings.simpletitle",
            listKey: "finance.savings.simpleExplanation",
          },
          {
            id: "examples",
            titleKey: "finance.savings.exampletitle",
            introKey: "finance.savings.exampleintro",
            listKey: "finance.savings.examplelist",
            contentKey: "finance.savings.examplecalc",
            endKey: "finance.savings.exampleNote",
          },
          {
            id: "why-use",
            titleKey: "finance.savings.whyUseTitle",
            subsections: [
              {
                id: "turning-habits",
                titleKey: "finance.savings.whyUsesubTitle",
                introKey: "finance.savings.whyUsesubpara",
                listKey: "finance.savings.whyUsesubList",
              },
            ],
          },
          {
            id: "how-to-use",
            titleKey: "finance.savings.howToUseTitle",
            introKey: "finance.savings.howToUseIntro",
            listKey: "finance.savings.howToUseList",
            endKey: "finance.savings.howToUseNote",
          },
          {
            id: "smart-tips",
            titleKey: "finance.savings.smartTipsTitle",
            introKey: "finance.savings.smartTipsIntro",
            listKey: "finance.savings.smartTipsList",
          },
        ],
      },
    ],

    faqTitleKey: "finance.savings.faqTitle",
    faqs: [
      { qKey: "finance.savings.faq.0.q", aKey: "finance.savings.faq.0.a" },
      { qKey: "finance.savings.faq.1.q", aKey: "finance.savings.faq.1.a" },
      { qKey: "finance.savings.faq.2.q", aKey: "finance.savings.faq.2.a" },
      { qKey: "finance.savings.faq.3.q", aKey: "finance.savings.faq.3.a" },
      { qKey: "finance.savings.faq.4.q", aKey: "finance.savings.faq.4.a" },
      { qKey: "finance.savings.faq.5.q", aKey: "finance.savings.faq.5.a" },
    ],
  },

  {
    slug: "compound-interest-calculator",
    metaTitleKey: "finance.compound.title",
    metaDescriptionKey: "finance.compound.desc",
    titleKey: "finance.compound.title",
    category: "Finance",
    descriptionKey: "finance.compound.desc",
    heading: "finance.compound.heading",
    formulaId: "compound",

    inputs: [
      { label: "finance.compound.principal", name: "principal", type: "number", unit: "$" },
      { label: "finance.compound.rate", name: "rate", type: "number", unit: "%" },
      { label: "finance.compound.years", name: "years", type: "number", unit: "years" },

      {
        label: "finance.compound.compounds",
        name: "compounds",
        type: "select",
        options: [
          { value: "1", label: "finance.compound.annually" },
          { value: "2", label: "finance.compound.semiannually" },
          { value: "4", label: "finance.compound.quarterly" },
          { value: "12", label: "finance.compound.monthly" },
          { value: "365", label: "finance.compound.daily" }
        ]
      },

      { label: "finance.compound.monthlyContribution", name: "monthlyContribution", type: "number", unit: "$" },

      {
        label: "finance.compound.contributionFrequency",
        name: "contributionFrequency",
        type: "select",
        options: [
          { value: "12", label: "finance.compound.freqMonthly" },
          { value: "4", label: "finance.compound.freqQuarterly" },
          { value: "1", label: "finance.compound.freqYearly" }
        ]
      },

      {
        label: "finance.compound.interestType",
        name: "interestType",
        type: "select",
        options: [
          { value: "compound", label: "finance.compound.typeCompound" },
          { value: "simple", label: "finance.compound.typeSimple" }
        ]
      },

      { label: "finance.compound.inflationRate", name: "inflationRate", type: "number", unit: "%" },

      { label: "finance.compound.taxRate", name: "taxRate", type: "number", unit: "%" },

      { label: "finance.compound.goalAmount", name: "goalAmount", type: "number", unit: "$" }
    ],

    result: {
      label: "finance.compound.result",
      explainKey: "finance.compound.resultExplain",
    },

    tocheading: "finance.compound.tocTitle",

    toc: [
      { id: "why-matters", labelKey: "finance.compound.tocwhy" },
      { id: "how-works", labelKey: "finance.compound.tochowitworks" },
      { id: "why-use", labelKey: "finance.compound.tocwhyuse" },
      { id: "step1", labelKey: "finance.compound.tocstep1" },
      { id: "step2", labelKey: "finance.compound.tocstep2" },
      { id: "examples", labelKey: "finance.compound.tocexample" },
      { id: "understanding", labelKey: "finance.compound.tocresults" },
      { id: "why-formula-works", labelKey: "finance.compound.tocwhyformula" },
    ],

    sections: [
      {
        id: "intro",
        titleKey: "finance.compound.section1Title",
        contentKey: "finance.compound.section1Content",
        subsections: [
          {
            id: "why-matters",
            titleKey: "finance.compound.section1WhyTitle",
            introKey: "finance.compound.section1WhyContent",
            listKey: "finance.compound.section1WhyList",
            endKey: "finance.compound.section1WhyEnd",
            linkparacontent: "finance.compound.section1WhyEnd",
            linkparaKey: "finance.compound.section1WhyLink",
            linkparaslug: "savings-calculator",
          },
          {
            id: "how-works",
            titleKey: "finance.compound.section2Title",
            contentKey: "finance.compound.section2Content",
            introKey: "finance.compound.section2Intro",
            listKey: "finance.compound.section2List",
            subsections: [
              {
                id: "calculator-shows",
                titleKey: "finance.compound.section2ShowsTitle",
                listKey: "finance.compound.section2ShowsList",
              }
            ],
            endKey: "finance.compound.section2End",
          },
          {
            id: "why-use",
            titleKey: "finance.compound.section3Title",
            introKey: "finance.compound.section3Content",
          },
        ]
      },

      {
        id: "formula",
        titleKey: "finance.compound.formulaTitle",
        introKey: "finance.compound.formulaIntro",
        subsections: [
          {
            id: "main-formula",
            titleKey: "finance.compound.mainFormulaTitle",
            formulaKey: "finance.compound.mainFormula",
            type: "formula",
            listKey: "finance.compound.formulaVariables",
            endKey: "finance.compound.formulaExplain",
          },
          {
            id: "formula-image",
            imageKey: "finance.compound.imageUrl",
            imageAltKey: "finance.compound.imageAlt",
          },
          {
            id: "step1",
            titleKey: "finance.compound.step1Title",
            contentKey: "finance.compound.step1Content",
            listKey: "finance.compound.step1List",
            endKey: "finance.compound.step1Extra",
          },
          {
            id: "step2",
            titleKey: "finance.compound.step2Title",
            formulaKey: "finance.compound.step2Formula",
            endKey: "finance.compound.step2Explain",
          },
          {
            id: "examples",
            titleKey: "finance.compound.exampleTitle",
            introKey: "finance.compound.exampleIntro",
            listKey: "finance.compound.exampleValues",
            subsections: [
              {
                id: "example-calculation",
                titleKey: "finance.compound.exampleStep1Title",
                formulas: [
                  "finance.compound.exampleCalcSteps",
                ],
              },
              {
                id: "interest-earned",
                titleKey: "finance.compound.exampleStep2Title",
                formulaKey: "finance.compound.exampleInterest",
              },
            ],
            endKey: "finance.compound.exampleConclusion",
          },
          {
            id: "comparing-frequencies",
            titleKey: "finance.compound.compareTitle",
            listKey: "finance.compound.compareList",
            endKey: "finance.compound.compareExplain",
          },
          {
            id: "understanding",
            titleKey: "finance.compound.usageTitle",
            listKey: "finance.compound.usageList",
          },
          {
            id: "why-formula-works",
            titleKey: "finance.compound.whyWorksTitle",
            contentKey: "finance.compound.whyWorksContent",
          }
        ]
      },
    ],

    faqTitleKey: "finance.compound.faqTitle",
    faqs: [
      { qKey: "finance.compound.faq.0.q", aKey: "finance.compound.faq.0.a" },
      { qKey: "finance.compound.faq.1.q", aKey: "finance.compound.faq.1.a" },
      { qKey: "finance.compound.faq.2.q", aKey: "finance.compound.faq.2.a" },
      { qKey: "finance.compound.faq.3.q", aKey: "finance.compound.faq.3.a" },
      { qKey: "finance.compound.faq.4.q", aKey: "finance.compound.faq.4.a" },
      { qKey: "finance.compound.faq.5.q", aKey: "finance.compound.faq.5.a" },
    ]
  },

  {
    slug: "tip-calculator",
    metaTitleKey: "finance.tip.title",
    metaDescriptionKey: "finance.tip.desc",
    titleKey: "finance.tip.title",
    category: "Finance",
    descriptionKey: "finance.tip.desc",
    heading: "finance.tip.heading",
    formulaId: "tip",

    inputs: [
      { label: "finance.tip.billAmount", name: "billAmount", type: "number", unit: "$" },
      { label: "finance.tip.tipPercent", name: "tipPercent", type: "number", unit: "%" },
      { label: "finance.tip.taxPercent", name: "taxPercent", type: "number", unit: "%" },
      { label: "finance.tip.people", name: "people", type: "number", unit: "people" },
      {
        label: "finance.tip.rounding", name: "rounding", type: "select",
        options: [
          { value: "none", label: "finance.tip.none" },
          { value: "roundTip", label: "finance.tip.roundTip" },
          { value: "roundTotal", label: "finance.tip.roundTotal" }
        ]
      }
    ],

    result: {
      label: "finance.tip.result",
      explainKey: "finance.tip.resultExplain",
    },
    tocheading: "finance.tip.tocTitle",
    toc: [
      { id: "why-useful", labelKey: "finance.tip.tocwhy" },
      { id: "how-works", labelKey: "finance.tip.tochowitworks" },
      { id: "why-use", labelKey: "finance.tip.tocwhyuse" },
      { id: "step1", labelKey: "finance.tip.tocstep1" },
      { id: "step2", labelKey: "finance.tip.tocstep2" },
      { id: "step3", labelKey: "finance.tip.tocstep3" },
      { id: "examples", labelKey: "finance.tip.tocexample" },
      { id: "why-formula-works", labelKey: "finance.tip.tocwhyformula" },
    ],

    sections: [
      {
        id: "intro",
        titleKey: "finance.tip.section1Title",
        contentKey: "finance.tip.section1Content",
        subsections: [
          {
            id: "why-useful",
            titleKey: "finance.tip.section1Sub1Title",
            introKey: "finance.tip.section1Sub1Intro",
            listKey: "finance.tip.section1Sub1List",
            endKey: "finance.tip.section1Sub1Text",
            linkparacontent: "finance.tip.section1Sub1Text",
            linkparaKey: "finance.tip.section1Sub1Link",
            linkparaslug: "discount-calculator",
          },
          {
            id: "how-works",
            titleKey: "finance.tip.section1Sub2Title",
            introKey: "finance.tip.section1Sub2Intro",
            listKey: "finance.tip.section1Sub2List",
            contentKey: "finance.tip.section1Sub2Text",
            listKey2: "finance.tip.section1Sub2EndList",
            endKey: "finance.tip.section1Sub2End",
          },
          {
            id: "why-use",
            titleKey: "finance.tip.section1Sub3Title",
            introKey: "finance.tip.section1Sub3Text",
          },
        ]
      },

      {
        id: "formula",
        titleKey: "finance.tip.sectionTitle",
        introKey: "finance.tip.sectionContent",
        subsections: [
          {
            id: "main-formula",
            contentKey: "finance.tip.formulaIntro",
            formulaKey: "finance.tip.formula",
            type: "formula",
            contentKey2: "finance.tip.totalIntro",
            formulaKey2: "finance.tip.totalFormula",
            endKey: "finance.tip.formulaText",
          },
          {
            id: "step1",
            titleKey: "finance.tip.step1Title",
            contentKey: "finance.tip.step1Content",
            formulaKey: "finance.tip.step1Formula",
          },
          {
            id: "step2",
            titleKey: "finance.tip.step2Title",
            contentKey: "finance.tip.step2Content",
            formulaKey: "finance.tip.step2Formula",
          },
          {
            id: "step3",
            titleKey: "finance.tip.step3Title",
            contentKey: "finance.tip.step3Content",
            formulaKey: "finance.tip.step3Formula",
            endKey: "finance.tip.step3Text",
          },
          {
            id: "formula-image",
            imageKey: "finance.tip.imageURL",
            imageAltKey: "finance.tip.imageAlt",
          },
          {
            id: "examples",
            titleKey: "finance.tip.exampleTitle",
            introKey: "finance.tip.exampleIntro",
            listKey: "finance.tip.exampleData",
            formulas: [
              "finance.tip.exampleStep1",
              "finance.tip.exampleStep2",
              "finance.tip.exampleStep3",
            ],
            endKey: "finance.tip.exampleText",
          },
          {
            id: "adjust-tip",
            titleKey: "finance.tip.adjustTipTitle",
            contentKey: "finance.tip.adjustTipContent",
            listKey: "finance.tip.adjustTipExamples",
            endKey: "finance.tip.adjustTipText",
          },
          {
            id: "why-formula-works",
            titleKey: "finance.tip.whyFormulaWorksTitle",
            contentKey: "finance.tip.whyFormulaWorksText",
          }
        ]
      },
    ],

    faqTitleKey: "finance.tip.faqTitle",
    faqs: [
      { qKey: "finance.tip.faq.0.q", aKey: "finance.tip.faq.0.a" },
      { qKey: "finance.tip.faq.1.q", aKey: "finance.tip.faq.1.a" },
      { qKey: "finance.tip.faq.2.q", aKey: "finance.tip.faq.2.a" },
      { qKey: "finance.tip.faq.3.q", aKey: "finance.tip.faq.3.a" },
      { qKey: "finance.tip.faq.4.q", aKey: "finance.tip.faq.4.a" },
      { qKey: "finance.tip.faq.5.q", aKey: "finance.tip.faq.5.a" },
    ]
  },

];